# Generated by Django 6.0 on 2025-12-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_id'),
        ('trips', '0002_remove_trip_reject_comment_remove_trip_rider_status_and_more'),
    ]

    operations = [
    ]
