# Generated by Django 6.0 on 2025-12-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_trip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointrip',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
