# Generated by Django 5.2.7 on 2025-12-16 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdriver',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riders.rider'),
        ),
    ]
