# Generated by Django 6.0 on 2025-12-17 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_car_id_alter_carcompany_id_alter_driver_id_and_more'),
        ('main', '0002_alter_city_id_alter_contact_id_alter_day_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='city',
        ),
        migrations.AddField(
            model_name='driver',
            name='cities',
            field=models.ManyToManyField(blank=True, to='main.city'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.car'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='licenses',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='national_id_or_iqama',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
