# Generated by Django 5.2.7 on 2025-12-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrider',
            name='user',
        ),
    ]
