# Generated by Django 6.0 on 2025-12-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0008_merge_20251224_1900'),
        ('riders', '0008_merge_20251224_2024'),
        ('riders', '0008_merge_20251224_2056'),
        ('riders', '0008_merge_20251224_2102'),
    ]

    operations = [
    ]
