# Generated by Django 5.2.7 on 2025-12-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_subscription', '0004_merge_20251224_0851'),
        ('trip_subscription', '0004_merge_20251224_0920'),
    ]

    operations = [
    ]
