# Generated by Django 6.0 on 2025-12-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_subscription', '0008_merge_20251224_1858'),
        ('trip_subscription', '0008_merge_20251224_2024'),
        ('trip_subscription', '0008_merge_20251224_2055'),
        ('trip_subscription', '0008_merge_20251224_2102'),
    ]

    operations = [
    ]
