# Generated by Django 5.2.7 on 2025-12-23 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_request', '0005_riderrequest_driver'),
        ('riders', '0004_alter_reviewrider_id_alter_rider_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequestTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reject_Comment', models.TextField(blank=True, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riders.rider')),
                ('rider_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider_request.riderrequest')),
            ],
        ),
    ]
