# Generated by Django 5.2.7 on 2025-12-23 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_request', '0006_joinrequesttrip'),
        ('riders', '0004_alter_reviewrider_id_alter_rider_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinrequesttrip',
            name='reject_Comment',
        ),
        migrations.AlterField(
            model_name='joinrequesttrip',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_submissions', to='riders.rider'),
        ),
        migrations.AlterField(
            model_name='joinrequesttrip',
            name='rider_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_join_requests', to='rider_request.riderrequest'),
        ),
    ]
